# Which vendors have the most trips, and what is the total revenue generated by that vendor?

from mrjob.job import MRJob
from mrjob.step import MRStep

class mapReduce(MRJob):

    def steps(self):
        return  [
            MRStep (mapper=self.mapper,
                    reducer=self.reducer),
            MRStep(reducer=self.max_vendor)
            ]

    def mapper(self, _, line):
        vals = line.strip().split(',')
        vendor_id = vals[0]
        if vendor_id != 'VendorID':
            revenue = float(vals[16])
            yield vendor_id, (1, revenue)


    def reducer(self, vendor , values):
        total_trips = 0
        total_rev = 0
        for trips,rev in values:
            total_trips += trips
            total_rev += rev
        total_rev = round(total_rev,2)
        yield None, (total_trips, total_rev, vendor)


    def max_vendor(self, _, values):
        max_trips, rev, vendor = max(values, key=lambda x: x[0])
        yield "Vendor with max trips : ", vendor
        yield "Trips : ", max_trips
        yield "Revenue generated : ", rev
 

if __name__ == '__main__':
    mapReduce.run()

