# Which vendors have the most trips, and what is the total revenue generated by that vendor?

# for storing outputs in hdfs : use this for powerbi integration activity
# python mrtask_a.py -r hadoop inputs --output-dir /user/hadoop/outputs/out_a.txt

# storing outputs in emr folder
# python mrtask_a.py -r hadoop inputs > outputs/out_a.txt

# local testing
# python mrtask_a.py inputs > outputs/out_a.txt

from mrjob.job import MRJob
from mrjob.step import MRStep

class mapReduce(MRJob):

    def steps(self):
        return  [
            MRStep (mapper=self.mapper,
                    reducer=self.reducer),
            MRStep(reducer=self.max_vendor)
            ]

    def mapper(self, _, line):
        vals = line.strip().split(',')
        vendor_id = vals[0]
        if vendor_id != 'VendorID':  # skipping the header row
            revenue = float(vals[10])  # revenue is the fare amount in the 10th column
            yield vendor_id, (1, revenue)  
            # yield the vendor_id as key and the tuple of trip count and revenue as values


    def reducer(self, vendor , values):
        # the reducer will yield the total number of trips and the total revenue generated by that vendor
        total_trips = 0
        total_rev = 0
        for trips,rev in values:
            total_trips += trips
            total_rev += rev
        total_rev = round(total_rev,2)
        yield None, (total_trips, total_rev, vendor)


    def max_vendor(self, _, values):
        # this reducer will yield the vendor with the max number of trips
        max_trips, rev, vendor = max(values, key=lambda x: x[0])    # finding the tuple with max trips
        yield "Vendor with max trips", vendor
        yield "Trips", max_trips
        yield "Revenue generated", rev
 

if __name__ == '__main__':
    mapReduce.run()

