# Which vendors have the most trips, and what is the total revenue generated by that vendor?

from mrjob.job import MRJob

class mapReduce(MRJob):
    def mapper(self, _, line):
        vals = line.strip().split(',')
        vendor_id = vals[0]
        revenue = float(vals[16])
        yield vendor_id, (1, revenue)


    def combiner(self, vendor , values):
        total_trips = 0
        total_rev = 0
        for trips,rev in values:
            total_trips += trips
            total_rev += rev
        yield None, (total_trips, total_rev, vendor)


    def reducer(self, _, values):
        max_trips, rev, vendor = max(values, key=lambda x: x[0])
        yield vendor, (max_trips, rev)


